
name: OptimizedSplitTunnel

label: Optimized_Split_Tunnel
description: GlobalProtect split tunnel of media App-IDs. Repeat to add additional apps.

type: panos


extends:

labels:
  collection:
    - GlobalProtect - Optimized Split Tunnel

variables:
  - name: gateway_name
    description: Name of the gateway
    default: Gateway-1
    type_hint: text
  - name: gateway_intf
    description: Interface mapped to the GP gateway (ethernet1/n)
    default: ethernet1/1
    type_hint: text
  - name: gateway_ip
    description: Gateway-1 - IP address mapped to the GP gateway
    default: 192.168.55.20/24
    type_hint: text
  - name: tunnel_name
    description: Name of the tunnel (tunnel.100)
    default: tunnel.100
    type_hint: text
  - name: streaming_app
    description: name of the streaming app
    default: netflix-streaming
    type_hint: dropdown
    dd_list:
      - key: netflix-streaming
        value: netflix-streaming
      - key: youtube-streaming
        value: youtube-streaming
      - key: sling
        value: sling
      - key: vimeo-base
        value: vimeo-base
      - key: xfinity-tv
        value: xfinity-tv
      - key: youku-base
        value: youku-base
      - key: hulu-base
        value: hulu-base
      - key: dailymotion
        value: dailymotion
  - name: trusted_root_ca_name
    description: Name of the Trusted Root CA
    default: GP-Root-CA
    type_hint: text

snippets:

  - name: apps
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/global-protect/global-protect-gateway
    file: apps.xml
  - name: decrypt
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/global-protect/global-protect-gateway
    file: decrypt.xml
